CREATE SCHEMA IF NOT EXISTS fitclub;

-- =====================================================
-- SOCIO
-- =====================================================

CREATE TABLE fitclub.socio (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               nombre VARCHAR(255) NOT NULL,
                               email VARCHAR(255) NOT NULL UNIQUE,
                               telefono VARCHAR(255) NOT NULL,
                               fecha_registro DATE NOT NULL
);

-- =====================================================
-- PLAN
-- =====================================================

CREATE TABLE fitclub.plan (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nombre VARCHAR(255) NOT NULL UNIQUE,
                              descripcion VARCHAR(255),
                              precio NUMERIC(12,2) NOT NULL,
                              duracion_dias INTEGER NOT NULL,

                              CONSTRAINT ck_plan_precio
                                  CHECK (precio > 0),

                              CONSTRAINT ck_plan_duracion
                                  CHECK (duracion_dias > 0)
);

-- =====================================================
-- INSTRUCTOR
-- =====================================================

CREATE TABLE fitclub.instructor (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    nombre VARCHAR(255) NOT NULL,
                                    email VARCHAR(255) NOT NULL UNIQUE,
                                    telefono VARCHAR(255) NOT NULL,
                                    especialidad VARCHAR(255) NOT NULL
);

-- =====================================================
-- CLASE
-- =====================================================

CREATE TABLE fitclub.clase (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               nombre VARCHAR(255) NOT NULL,
                               descripcion VARCHAR(255),
                               cupo_maximo INTEGER NOT NULL,

                               CONSTRAINT ck_clase_cupo
                                   CHECK (cupo_maximo > 0)
);

-- =====================================================
-- MEMBRESIA
-- =====================================================

CREATE TABLE fitclub.membresia (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   socio_id BIGINT NOT NULL,
                                   plan_id BIGINT NOT NULL,
                                   fecha_inicio DATE NOT NULL,
                                   fecha_fin DATE NOT NULL,
                                   estado VARCHAR(30) NOT NULL,

                                   CONSTRAINT fk_membresia_socio
                                       FOREIGN KEY (socio_id)
                                           REFERENCES fitclub.socio(id),

                                   CONSTRAINT fk_membresia_plan
                                       FOREIGN KEY (plan_id)
                                           REFERENCES fitclub.plan(id),

                                   CONSTRAINT ck_membresia_fechas
                                       CHECK (fecha_fin >= fecha_inicio),

                                   CONSTRAINT ck_membresia_estado
                                       CHECK (estado IN (
                                                         'ACTIVA',
                                                         'VENCIDA',
                                                         'SUSPENDIDA',
                                                         'CANCELADA'
                                           ))
);

-- =====================================================
-- HORARIO CLASE
-- =====================================================

CREATE TABLE fitclub.horario_clase (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       clase_id BIGINT NOT NULL,
                                       instructor_id BIGINT NOT NULL,
                                       fecha DATE NOT NULL,
                                       hora_inicio TIME NOT NULL,
                                       hora_fin TIME NOT NULL,

                                       CONSTRAINT fk_horario_clase
                                           FOREIGN KEY (clase_id)
                                               REFERENCES fitclub.clase(id),

                                       CONSTRAINT fk_horario_instructor
                                           FOREIGN KEY (instructor_id)
                                               REFERENCES fitclub.instructor(id),

                                       CONSTRAINT ck_horario_horas
                                           CHECK (hora_fin > hora_inicio)
);

-- =====================================================
-- RESERVA CLASE
-- =====================================================

CREATE TABLE fitclub.reserva_clase (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       socio_id BIGINT NOT NULL,
                                       horario_clase_id BIGINT NOT NULL,
                                       fecha_reserva TIMESTAMP NOT NULL,
                                       estado VARCHAR(30) NOT NULL,

                                       CONSTRAINT fk_reserva_socio
                                           FOREIGN KEY (socio_id)
                                               REFERENCES fitclub.socio(id),

                                       CONSTRAINT fk_reserva_horario
                                           FOREIGN KEY (horario_clase_id)
                                               REFERENCES fitclub.horario_clase(id),

                                       CONSTRAINT ck_reserva_estado
                                           CHECK (estado IN (
                                                             'ACTIVA',
                                                             'CANCELADA'
                                               ))
);

-- Evita dos reservas activas del mismo socio
-- para el mismo horario.
CREATE UNIQUE INDEX uq_reserva_activa_socio_horario
    ON fitclub.reserva_clase (socio_id, horario_clase_id)
    WHERE estado = 'ACTIVA';

-- =====================================================
-- ASISTENCIA
-- =====================================================

CREATE TABLE fitclub.asistencia (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    reserva_clase_id BIGINT NOT NULL UNIQUE,
                                    fecha_registro TIMESTAMP NOT NULL,
                                    presente BOOLEAN NOT NULL,

                                    CONSTRAINT fk_asistencia_reserva
                                        FOREIGN KEY (reserva_clase_id)
                                            REFERENCES fitclub.reserva_clase(id)
);

-- =====================================================
-- HISTORIAL MEMBRESIA
-- =====================================================

CREATE TABLE fitclub.historial_membresia (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             membresia_id BIGINT NOT NULL,
                                             estado_anterior VARCHAR(30),
                                             estado_nuevo VARCHAR(30) NOT NULL,
                                             fecha_cambio TIMESTAMP NOT NULL,
                                             motivo VARCHAR(255),

                                             CONSTRAINT fk_historial_membresia
                                                 FOREIGN KEY (membresia_id)
                                                     REFERENCES fitclub.membresia(id),

                                             CONSTRAINT ck_historial_estado_anterior
                                                 CHECK (
                                                     estado_anterior IS NULL
                                                         OR estado_anterior IN (
                                                                                'ACTIVA',
                                                                                'VENCIDA',
                                                                                'SUSPENDIDA',
                                                                                'CANCELADA'
                                                         )
                                                     ),

                                             CONSTRAINT ck_historial_estado_nuevo
                                                 CHECK (
                                                     estado_nuevo IN (
                                                                      'ACTIVA',
                                                                      'VENCIDA',
                                                                      'SUSPENDIDA',
                                                                      'CANCELADA'
                                                         )
                                                     )
);

-- =====================================================
-- NOTIFICACION
-- =====================================================

CREATE TABLE fitclub.notificacion (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      socio_id BIGINT NOT NULL,
                                      titulo VARCHAR(255) NOT NULL,
                                      mensaje VARCHAR(1000) NOT NULL,
                                      fecha_envio TIMESTAMP NOT NULL,
                                      leida BOOLEAN NOT NULL,

                                      CONSTRAINT fk_notificacion_socio
                                          FOREIGN KEY (socio_id)
                                              REFERENCES fitclub.socio(id)
);

-- =====================================================
-- INDICES
-- =====================================================

CREATE INDEX ix_membresia_socio
    ON fitclub.membresia (socio_id);

CREATE INDEX ix_membresia_plan
    ON fitclub.membresia (plan_id);

CREATE INDEX ix_membresia_estado
    ON fitclub.membresia (estado);

CREATE INDEX ix_horario_clase
    ON fitclub.horario_clase (clase_id);

CREATE INDEX ix_horario_instructor
    ON fitclub.horario_clase (instructor_id);

CREATE INDEX ix_horario_fecha
    ON fitclub.horario_clase (fecha);

CREATE INDEX ix_reserva_socio
    ON fitclub.reserva_clase (socio_id);

CREATE INDEX ix_reserva_horario
    ON fitclub.reserva_clase (horario_clase_id);

CREATE INDEX ix_historial_membresia
    ON fitclub.historial_membresia (membresia_id);

CREATE INDEX ix_notificacion_socio
    ON fitclub.notificacion (socio_id);