CREATE TABLE fitclub.usuario (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 nombre VARCHAR(255) NOT NULL,
                                 email VARCHAR(255) NOT NULL UNIQUE,
                                 password VARCHAR(255) NOT NULL,
                                 rol VARCHAR(30) NOT NULL,
                                 activo BOOLEAN NOT NULL DEFAULT TRUE,

                                 CONSTRAINT ck_usuario_rol
                                     CHECK (rol IN (
                                                    'ADMINISTRADOR',
                                                    'RECEPCION',
                                                    'INSTRUCTOR',
                                                    'SOCIO'
                                         ))
);

CREATE INDEX ix_usuario_rol
    ON fitclub.usuario (rol);